# Site settings
title: EEB 177/234 - Discussion 
email: gkandlikar@ucla.edu
description: > # this means to ignore newlines until "baseurl:"
  Course website for the Discussion section of UCLA EEB-177/234  <br>
  (Practical Computing for Ecology and Evolutionary Biology)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gauravsk.github.io/eeb177-W17" # the base hostname & protocol for your site
twitter_username: 
github_username:  gauravsk
exclude: weekly_content
theme: jekyll-theme-time-machine
paginate: 10
# Build settings
markdown: kramdown