# Site settings
title: EEB 177/234 - Discussion 
email: gkandlikar@ucla.edu
description: > # this means to ignore newlines until "baseurl:"
  This is the course website for the Discussion section of UCLA W17 EEB-177/234 
  (Practical Computing for Ecology and Evolutionary Biology).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://eeb177-w17.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  gauravsk
exclude: weekly_content, hw_files

# Build settings
markdown: kramdown
